const tracks = [
    {
      title: "Guilt",
      titleSpan: "",
      author: "Nero",
      album: "Welcome Reality",
      time: "4:44",
      year: "1990",
      genre: "uknown",
    },
    {
      title: "Elektro",
      titleSpan: "",
      author: "Dynoro, Outwork, Mr. Gee",
      album: "Elektro",
      time: "2:22",
      year: "1991",
      genre: "uknown",
    },
    {
      title: "I’m Fire",
      titleSpan: "",
      author: "Ali Bakgor",
      album: "I’m Fire",
      time: "2:22",
      year: "1992",
      genre: "uknown",
    },
    {
      title: "Non Stop",
      titleSpan: "(Remix)",
      author: "Стоункат, Psychopath",
      album: "Non Stop",
      time: "4:12",
      year: "1993",
      genre: "uknown",
    },
    {
      title: "Run Run",
      titleSpan: "(feat. AR/CO)",
      author: "Jaded, Will Clarke, AR/CO",
      album: "Run Run",
      time: "2:54",
      year: "1994",
      genre: "uknown",
    },
    {
      title: "Eyes on Fire",
      titleSpan: "(Zeds Dead Remix)",
      author: "Blue Foundation, Zeds Dead",
      album: "Eyes on Fire",
      time: "5:20",
      year: "1995",
      genre: "uknown",
    },
    {
      title: "Mucho Bien",
      titleSpan: "(Hi Profile Remix)",
      author: "HYBIT, Mr. Black, Offer Nissim, Hi Profile",
      album: "Mucho Bien",
      time: "3:41",
      year: "1996",
      genre: "uknown",
    },
    {
      title: "Knives n Cherries",
      titleSpan: "",
      author: "minthaze",
      album: "Captivating",
      time: "1:48",
      year: "1997",
      genre: "uknown",
    },
    {
      title: "How Deep Is Your Love",
      titleSpan: "",
      author: "Calvin Harris, Disciples",
      album: "How Deep Is Your Love",
      time: "3:32",
      year: "1998",
      genre: "uknown",
    },
    {
      title: "Morena",
      titleSpan: "",
      author: "Tom Boxer",
      album: "Soundz Made in Romania",
      time: "3:36",
      year: "1999",
      genre: "uknown",
    },
    {
      title: "",
      titleSpan: "",
      author: "",
      album: "",
      time: "",
      year: "",
      genre: "",
    }
  ]

  export default tracks;